[tool.poetry]
name = "dontavious"
version = "0.1.0"
description = ""
authors = ["tanmay-devv <tanmaysharma3141@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
